# .github/workflows/update-cask.yml
name: 🪄Auto-update swiftDialog Cask

on:
  schedule:
    - cron: "0 6 * * *"  # daily at 6am UTC
  workflow_dispatch:

jobs:
  update-cask:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - name: Checkout tap repo
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Run build_cask.rb
        run: ./scripts/build_cask.rb

      - name: Extract version from Cask
        id: get_version
        run: |
          VERSION=$(grep 'version "' Casks/swiftdialog.rb | cut -d'"' -f2)
          echo "version_tag=v$VERSION" >> "$GITHUB_OUTPUT"

      - name: Auto-commit updated Cask and tag
        id: auto-commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update swiftDialog Cask to ${{ steps.get_version.outputs.version_tag }}"
          file_pattern: "Casks/swiftdialog.rb"
          tagging_message: ${{ steps.get_version.outputs.version_tag }}